name: "AZD Deploy Workflow"

on: 
  workflow_dispatch:
  push:
    branches:
      - main  # Replace with your branch if different
  pull_request:
    branches:
      - main  # Replace with your branch if different

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: "Build and deploy to Azure"
    runs-on: ubuntu-latest
    concurrency: 
      group: azd-deploy
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Azure DevOps CLI
        run: |
          curl -fsSL https://aka.ms/install-azd.sh | bash
      - name: Log into Azure and Initialize Project
        run: |
          azd auth login --client-id 'b3e7364d-5fa2-4ea7-a176-87483b8183c8' --client-secret ${{ secrets.CLIENT_SECRET }} --tenant-id '16b3c013-d300-468d-ac64-7eda0820b6d3'
          yes | azd up --environment aoai-vectorsearch-chatgpt-dev
